<% require "uri" %>

db_config: &db_config
  <% if ENV["DATABASE_URL"].present? %>
  <% uri = URI.parse(ENV["DATABASE_URL"]) if ENV["DATABASE_URL"].present? %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  host:     <%= uri.host %>
  <% else %>
  username: root
  password: 'swah1234'
  host: localhost
  <% end %>
  adapter: mysql2
  pool: 10
  timeout: 5000
  port: 3306

development:
  <<: *db_config
  database: penblades_development
  encoding: utf8mb4
  collation: utf8mb4_bin

test:
  <<: *db_config
  database: penblades_test
  encoding: utf8mb4
  collation: utf8mb4_bin

staging:
  <<: *db_config
  database: penblades_staging
  encoding: utf8mb4
  collation: utf8mb4_bin

production:
  <<: *db_config
  database: penblades_production
  encoding: utf8mb4
  collation: utf8mb4_bin